cores: 30
resources:
  - mem_swap=3500
configfile: dataflow-config.yaml
snakefile: ./workflow/Snakefile-build-raw
keep-going: true
rerun-incomplete: true
config:
  - system=lngs
  - XDG_CACHE_HOME=.snakemake/cache
